[workspace]
resolver = "2"

members = [
    "trading-engine/*",
    "quantlib",
    "examples/*",
]

[workspace.dependencies]
num-format = "0.4.0"
tracing = "0.1.25"

# dev-dependencies
criterion = { version = "0.5.1"}


