[workspace]
resolver = "2"

members = [
    "quantlib",
    "trading-engine",
    "examples/*",
]


[workspace.dependencies]
num-format = "0.4.0"
tracing = "0.1.25"
chrono = "0.4"
minstant = "0.1"
criterion = { version = "0.5.1"}
