[package]
name = "trading-engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "trading_engine"

#[[bench]]
#name = "timer"
#harness = false

[[bench]]
name = "formatter"
harness = false

#[[bench]]
#name = "ustr"
#harness = false

#[[bench]]
#name = "arithematics"
#harness = false



[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
rstest = "0.21"
minstant = { version = "0.1" }#, features = ["fallback-coarse"] }
quanta = "0.12"
criterion = "0.5"
time = { version = "0.3", features = ["macros", "serde", "formatting", "parsing", "local-offset"] }
chrono = { version = "0.4", features = ["serde"] }
lazy_format = "2.0"
joinery = "3.1" 
crossbeam-channel = "0.5"
hashbrown = "0.14"
enum_dispatch = "0.3"
arc-swap = "1.7"
ustr = "1.0"
once_cell = "1.19"
core_affinity = "0.8"