[package]
name = "quantlib"
version = "0.1.0"
edition = "2021"

[lib]
name = "quantlib"

[dependencies]
time = { version = "0.3.20", features = ["macros"]}
simba = "0.8.1"
korean-lunar-calendar = "1.0.0"
chrono = "0.4.33"
log = "0.4.14"
criterion = "0.5.1"
num-traits = "0.2.18"
assert_approx_eq = "1.1.0"
regex = "1.10.3"

[dev-dependencies]
rstest = "0.18.2"

[[bench]]
name = "find_index"
harness = false