[package]
name = "quantlib"
version = "0.1.0"
edition = "2021"

[lib]
name = "quantlib"

[dependencies]
korean-lunar-calendar = "1.0.0"
chrono = { version = "0.4.19", features = ["serde"] }
time = { version = "0.3.20", features = ["macros"]}
log = "0.4.14"
simba = "0.8.1"