[package]
name = "quantlib"
version = "0.1.0"
edition = "2021"

[lib]
name = "quantlib"

[dependencies]
time = { version = "0.3.20", features = ["macros"]}
simba = "0.8.1"
korean-lunar-calendar = "1.0.0"
chrono = "0.4.33"
log = "0.4.14"
