[package]
name = "examples-prototype"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
minstant = { version = "0.1", features = ["fallback-coarse"] }
time = { version = "0.3", features = ["macros"]}
fastdate = "0.3"
