[package]
name = "examples-atomic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
trading-engine = { version = "0.1", path = "../../trading-engine" }
parking_lot = "0.12"
anyhow = "1.0"
core_affinity = "0.8"
criterion = "0.5"