[package]
name = "examples-mem-investigation"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
quantlib = { version = "0.1", path = "../../quantlib" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustc-hash = "2.0"